language: r

sudo: required

apt_packages:
 - r-cran-rjava

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
 - keboola/redshift-r-client

notifications:
  slack:
    secure: NwSrZqSGTQ8caNRSz73vIIK648L9CIXvlhWXPd4AY1lxYG9Z8Q2nV564Z5sgpmQT1h7mMugyHJOy0re7aFrh7MDfs7J5fakie0NKedZPCgakSVyEYSomdmP8fkTpd/RZQq6kqjR3H2a+RL1Rp2gYpshHD2ksfqr4tuXpTQKI/u8=
  email: false
